<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'PhpClientPoeditor\Controller\BuildController'       => __DIR__ . '/src/PhpClientPoeditor/Controller/BuildController.php',
    'PhpClientPoeditor\Exception\DomainException'        => __DIR__ . '/src/PhpClientPoeditor/Exception/DomainException.php',
    'PhpClientPoeditor\Exception\ExceptionInterface'     => __DIR__ . '/src/PhpClientPoeditor/Exception/ExceptionInterface.php',
    'PhpClientPoeditor\Exception\RuntimeException'       => __DIR__ . '/src/PhpClientPoeditor/Exception/RuntimeException.php',
    'PhpClientPoeditor\Module'                           => __DIR__ . '/src/PhpClientPoeditor/Module.php',
    'PhpClientPoeditor\Options\Options'                  => __DIR__ . '/src/PhpClientPoeditor/Options/Options.php',
    'PhpClientPoeditor\Options\OptionsFactory'           => __DIR__ . '/src/PhpClientPoeditor/Options/OptionsFactory.php',
    'PhpClientPoeditor\Service\ClientService'            => __DIR__ . '/src/PhpClientPoeditor/Service/ClientService.php',
    'PhpClientPoeditor\Service\ClientServiceFactory'     => __DIR__ . '/src/PhpClientPoeditor/Service/ClientServiceFactory.php',
    'PhpClientPoeditor\Strategy\AbstractStrategy'        => __DIR__ . '/src/PhpClientPoeditor/Strategy/AbstractStrategy.php',
    'PhpClientPoeditor\Strategy\OneToOneStrategy'        => __DIR__ . '/src/PhpClientPoeditor/Strategy/OneToOneStrategy.php',
    'PhpClientPoeditor\Strategy\OneToOneStrategyFactory' => __DIR__ . '/src/PhpClientPoeditor/Strategy/OneToOneStrategyFactory.php',
    'PhpClientPoeditor\Strategy\PhpArrayStrategy'        => __DIR__ . '/src/PhpClientPoeditor/Strategy/PhpArrayStrategy.php',
    'PhpClientPoeditor\Strategy\PhpArrayStrategyFactory' => __DIR__ . '/src/PhpClientPoeditor/Strategy/PhpArrayStrategyFactory.php',
    'PhpClientPoeditor\Strategy\StrategyInterface'       => __DIR__ . '/src/PhpClientPoeditor/Strategy/StrategyInterface.php',
);
